name: Test Python Examples

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Python Examples
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/developer-hub-python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set up poetry
        uses: Gr1N/setup-poetry@v9
      - name: Install dependencies
        run: poetry install --with dev
      - name: Format with ruff
        run: poetry run ruff format --diff
      - name: Lint with ruff
        run: poetry run ruff check --diff
      - name: Run tests
        run: poetry run pytest -v
